name: "Greet Hardworker"

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GIT_PATH }}
          issue-message: |
            👋 Hey there, hard worker!
            “Success usually comes to those who are too busy to be looking for it.” – Henry David Thoreau
          pr-message: |
            🎉 Congrats on your PR!
            “Don’t watch the clock; do what it does. Keep going.” – Sam Levenson
