name: Greets Action

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: Manoj-Paramsetti/greets-action@main
        if: ${{ github.event.pull_request.merged == true }}
        with:
          GITHUB_TOKEN: ${{ secrets.GIT_BOT }}
          # here issue_message is not given since the condition checks for the merge is true. it will
          # does not pass the checks in issue
          PR_message: 'add a message over here for the pull request'
           
      - uses: Manoj-Paramsetti/greets-action@main
        if: ${{ github.event.pull_request.merged == false}}
        with:
          GITHUB_TOKEN: ${{ secrets.GIT_BOT }}
          issue_message: 'add message over here for issue'
          pr_message: 'add message over here for pull request'
          # labels is not a required key. you can use it when you want to add labels. it supports
          # more than 4 labels
          labels: '["label_1", "label_2", "label_3"]' 
          