name: "Greet on Pull Request"

on:
  pull_request:
    types: [opened]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GIT_PATH }}
          pr-message: |
            🎉 **Thanks for opening a Pull Request!**  
            “Success is the sum of small efforts repeated day in and day out.” – Robert Collier  
            Keep up the great work! 💪
