name: Update All Branches with Main

on:
  push:
    branches:
      - main

jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0  # fetch the entire history so all branches are available

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Get list of branches and merge main into each
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PATH }}
        run: |
          # Fetch all branches
          git fetch --all

          # Get a list of remote branches (excluding main)
          branches=$(git branch -r | grep -v 'origin/main' | sed 's/ *origin\///')
          echo "Found branches: $branches"
          
          for branch in $branches; do
            echo "Processing branch: $branch"

            # Checkout the branch
            git checkout $branch

            # Merge main into the branch without prompting for a commit message
            merge_output=$(git merge origin/main --no-edit 2>&1)
            echo "$merge_output"

            # Check for conflicts by looking for merge conflict markers in the output
            if echo "$merge_output" | grep -q 'CONFLICT'; then
              echo "Merge conflicts detected in branch $branch. Skipping push. Please resolve manually."
              continue
            fi

            # Push the branch if merge was successful
            git push origin $branch
          done
